class Municipio {
  final String nombre;

  const Municipio(this.nombre);
}

class Departamento {
  final String nombre;
  final List<Municipio> municipios;

  const Departamento({required this.nombre, required this.municipios});
}

/// Lista de referencia de la división político-administrativa de Honduras.
/// Si falta o sobra algún municipio, este es el único lugar que hay que tocar.
class Departamentos {
  static const List<Departamento> lista = [
    Departamento(
      nombre: 'Atlántida',
      municipios: [
        Municipio('La Ceiba'),
        Municipio('El Porvenir'),
        Municipio('Esparta'),
        Municipio('Jutiapa'),
        Municipio('La Masica'),
        Municipio('San Francisco'),
        Municipio('Tela'),
        Municipio('Arizona'),
      ],
    ),
    Departamento(
      nombre: 'Choluteca',
      municipios: [
        Municipio('Choluteca'),
        Municipio('Apacilagua'),
        Municipio('Concepción de María'),
        Municipio('Duyure'),
        Municipio('El Corpus'),
        Municipio('El Triunfo'),
        Municipio('Marcovia'),
        Municipio('Morolica'),
        Municipio('Namasigüe'),
        Municipio('Orocuina'),
        Municipio('Pespire'),
        Municipio('San Antonio de Flores'),
        Municipio('San Isidro'),
        Municipio('San José'),
        Municipio('San Marcos de Colón'),
        Municipio('Santa Ana de Yusguare'),
      ],
    ),
    Departamento(
      nombre: 'Colón',
      municipios: [
        Municipio('Trujillo'),
        Municipio('Balfate'),
        Municipio('Iriona'),
        Municipio('Limón'),
        Municipio('Sabá'),
        Municipio('Santa Fe'),
        Municipio('Santa Rosa de Aguán'),
        Municipio('Sonaguera'),
        Municipio('Tocoa'),
        Municipio('Bonito Oriental'),
      ],
    ),
    Departamento(
      nombre: 'Comayagua',
      municipios: [
        Municipio('Comayagua'),
        Municipio('Ajuterique'),
        Municipio('El Rosario'),
        Municipio('Esquías'),
        Municipio('Humuya'),
        Municipio('La Libertad'),
        Municipio('La Trinidad'),
        Municipio('Lamaní'),
        Municipio('Lejamaní'),
        Municipio('Meámbar'),
        Municipio('Minas de Oro'),
        Municipio('Ojos de Agua'),
        Municipio('San Jerónimo'),
        Municipio('San José de Comayagua'),
        Municipio('San José del Potrero'),
        Municipio('San Luis'),
        Municipio('San Sebastián'),
        Municipio('Siguatepeque'),
        Municipio('Villa de San Antonio'),
        Municipio('Las Lajas'),
        Municipio('Taulabé'),
      ],
    ),
    Departamento(
      nombre: 'Copán',
      municipios: [
        Municipio('Santa Rosa de Copán'),
        Municipio('Cabañas'),
        Municipio('Concepción'),
        Municipio('Copán Ruinas'),
        Municipio('Corquín'),
        Municipio('Cucuyagua'),
        Municipio('Dolores'),
        Municipio('Dulce Nombre'),
        Municipio('El Paraíso'),
        Municipio('Florida'),
        Municipio('La Jigua'),
        Municipio('La Unión'),
        Municipio('Nueva Arcadia'),
        Municipio('San Agustín'),
        Municipio('San Antonio'),
        Municipio('San Jerónimo'),
        Municipio('San José'),
        Municipio('San Juan de Opoa'),
        Municipio('San Nicolás'),
        Municipio('San Pedro'),
        Municipio('Santa Rita'),
        Municipio('Trinidad de Copán'),
        Municipio('Veracruz'),
      ],
    ),
    Departamento(
      nombre: 'Cortés',
      municipios: [
        Municipio('San Pedro Sula'),
        Municipio('Choloma'),
        Municipio('La Lima'),
        Municipio('Omoa'),
        Municipio('Pimienta'),
        Municipio('Potrerillos'),
        Municipio('Puerto Cortés'),
        Municipio('San Antonio de Cortés'),
        Municipio('San Francisco de Yojoa'),
        Municipio('San Manuel'),
        Municipio('Santa Cruz de Yojoa'),
        Municipio('Villanueva'),
      ],
    ),
    Departamento(
      nombre: 'El Paraíso',
      municipios: [
        Municipio('Yuscarán'),
        Municipio('Alauca'),
        Municipio('Danlí'),
        Municipio('El Paraíso'),
        Municipio('Güinope'),
        Municipio('Jacaleapa'),
        Municipio('Liure'),
        Municipio('Morocelí'),
        Municipio('Oropolí'),
        Municipio('Potrerillos'),
        Municipio('San Antonio de Flores'),
        Municipio('San Lucas'),
        Municipio('San Matías'),
        Municipio('Soledad'),
        Municipio('Teupasenti'),
        Municipio('Texiguat'),
        Municipio('Vado Ancho'),
        Municipio('Yauyupe'),
        Municipio('Trojes'),
      ],
    ),
    Departamento(
      nombre: 'Francisco Morazán',
      municipios: [
        Municipio('Distrito Central'),
        Municipio('Alubarén'),
        Municipio('Cedros'),
        Municipio('Curarén'),
        Municipio('El Porvenir'),
        Municipio('Guaimaca'),
        Municipio('La Libertad'),
        Municipio('La Venta'),
        Municipio('Lepaterique'),
        Municipio('Maraita'),
        Municipio('Marale'),
        Municipio('Nueva Armenia'),
        Municipio('Ojojona'),
        Municipio('Orica'),
        Municipio('Reitoca'),
        Municipio('Sabanagrande'),
        Municipio('San Antonio de Oriente'),
        Municipio('San Buenaventura'),
        Municipio('San Ignacio'),
        Municipio('San Juan de Flores'),
        Municipio('San Miguelito'),
        Municipio('Santa Ana'),
        Municipio('Santa Lucía'),
        Municipio('Talanga'),
        Municipio('Tatumbla'),
        Municipio('Valle de Ángeles'),
        Municipio('Vallecillo'),
        Municipio('Villa de San Francisco'),
      ],
    ),
    Departamento(
      nombre: 'Gracias a Dios',
      municipios: [
        Municipio('Puerto Lempira'),
        Municipio('Ahuas'),
        Municipio('Brus Laguna'),
        Municipio('Juan Francisco Bulnes'),
        Municipio('Ramón Villeda Morales'),
        Municipio('Wampusirpi'),
      ],
    ),
    Departamento(
      nombre: 'Intibucá',
      municipios: [
        Municipio('La Esperanza'),
        Municipio('Camasca'),
        Municipio('Colomoncagua'),
        Municipio('Concepción'),
        Municipio('Dolores'),
        Municipio('Intibucá'),
        Municipio('Jesús de Otoro'),
        Municipio('Magdalena'),
        Municipio('Masaguara'),
        Municipio('San Antonio'),
        Municipio('San Isidro'),
        Municipio('San Juan'),
        Municipio('San Marcos de la Sierra'),
        Municipio('San Miguelito'),
        Municipio('Santa Lucía'),
        Municipio('Yamaranguila'),
        Municipio('San Francisco de Opalaca'),
      ],
    ),
    Departamento(
      nombre: 'Islas de la Bahía',
      municipios: [
        Municipio('Roatán'),
        Municipio('Guanaja'),
        Municipio('José Santos Guardiola'),
        Municipio('Utila'),
      ],
    ),
    Departamento(
      nombre: 'La Paz',
      municipios: [
        Municipio('La Paz'),
        Municipio('Aguanqueterique'),
        Municipio('Cabañas'),
        Municipio('Cane'),
        Municipio('Chinacla'),
        Municipio('Guajiquiro'),
        Municipio('Lauterique'),
        Municipio('Marcala'),
        Municipio('Mercedes de Oriente'),
        Municipio('Opatoro'),
        Municipio('San Antonio del Norte'),
        Municipio('San Juan'),
        Municipio('San José'),
        Municipio('San Pedro de Tutule'),
        Municipio('Santa Ana'),
        Municipio('Santa Elena'),
        Municipio('Santa María'),
        Municipio('Santiago de Puringla'),
        Municipio('Yarula'),
      ],
    ),
    Departamento(
      nombre: 'Lempira',
      municipios: [
        Municipio('Gracias'),
        Municipio('Belén'),
        Municipio('Candelaria'),
        Municipio('Cololaca'),
        Municipio('Erandique'),
        Municipio('Gualcince'),
        Municipio('Guarita'),
        Municipio('La Campa'),
        Municipio('La Iguala'),
        Municipio('La Unión'),
        Municipio('La Virtud'),
        Municipio('Las Flores'),
        Municipio('Lepaera'),
        Municipio('Mapulaca'),
        Municipio('Piraera'),
        Municipio('San Andrés'),
        Municipio('San Francisco'),
        Municipio('San Juan Guarita'),
        Municipio('San Manuel Colohete'),
        Municipio('San Marcos de Caiquín'),
        Municipio('San Rafael'),
        Municipio('San Sebastián'),
        Municipio('Santa Cruz'),
        Municipio('Talgua'),
        Municipio('Tambla'),
        Municipio('Tomalá'),
        Municipio('Valladolid'),
        Municipio('Virginia'),
      ],
    ),
    Departamento(
      nombre: 'Ocotepeque',
      municipios: [
        Municipio('Nueva Ocotepeque'),
        Municipio('Belén Gualcho'),
        Municipio('Concepción'),
        Municipio('Dolores Merendón'),
        Municipio('Fraternidad'),
        Municipio('La Encarnación'),
        Municipio('La Labor'),
        Municipio('Lucerna'),
        Municipio('Mercedes'),
        Municipio('San Fernando'),
        Municipio('San Francisco del Valle'),
        Municipio('San Jorge'),
        Municipio('San Marcos'),
        Municipio('Santa Fe'),
        Municipio('Sensenti'),
        Municipio('Sinuapa'),
      ],
    ),
    Departamento(
      nombre: 'Olancho',
      municipios: [
        Municipio('Juticalpa'),
        Municipio('Campamento'),
        Municipio('Catacamas'),
        Municipio('Concordia'),
        Municipio('Dulce Nombre de Culmí'),
        Municipio('El Rosario'),
        Municipio('Esquipulas del Norte'),
        Municipio('Gualaco'),
        Municipio('Guarizama'),
        Municipio('Guata'),
        Municipio('Guayape'),
        Municipio('Jano'),
        Municipio('La Unión'),
        Municipio('Mangulile'),
        Municipio('Manto'),
        Municipio('Patuca'),
        Municipio('Salamá'),
        Municipio('San Esteban'),
        Municipio('San Francisco de Becerra'),
        Municipio('San Francisco de la Paz'),
        Municipio('Santa María del Real'),
        Municipio('Silca'),
        Municipio('Yocón'),
      ],
    ),
    Departamento(
      nombre: 'Santa Bárbara',
      municipios: [
        Municipio('Santa Bárbara'),
        Municipio('Arada'),
        Municipio('Atima'),
        Municipio('Azacualpa'),
        Municipio('Ceguaca'),
        Municipio('Concepción del Norte'),
        Municipio('Concepción del Sur'),
        Municipio('Chinda'),
        Municipio('El Níspero'),
        Municipio('Gualala'),
        Municipio('Ilama'),
        Municipio('Macuelizo'),
        Municipio('Naranjito'),
        Municipio('Nuevo Celilac'),
        Municipio('Petoa'),
        Municipio('Protección'),
        Municipio('Quimistán'),
        Municipio('San Francisco de Ojuera'),
        Municipio('San José de Colinas'),
        Municipio('San Luis'),
        Municipio('San Marcos'),
        Municipio('San Nicolás'),
        Municipio('San Pedro Zacapa'),
        Municipio('San Vicente Centenario'),
        Municipio('Santa Rita'),
        Municipio('Trinidad'),
        Municipio('Las Vegas'),
      ],
    ),
    Departamento(
      nombre: 'Valle',
      municipios: [
        Municipio('Nacaome'),
        Municipio('Alianza'),
        Municipio('Amapala'),
        Municipio('Aramecina'),
        Municipio('Caridad'),
        Municipio('Goascorán'),
        Municipio('Langue'),
        Municipio('San Francisco de Coray'),
        Municipio('San Lorenzo'),
      ],
    ),
    Departamento(
      nombre: 'Yoro',
      municipios: [
        Municipio('Yoro'),
        Municipio('Arenal'),
        Municipio('El Negrito'),
        Municipio('El Progreso'),
        Municipio('Jocón'),
        Municipio('Morazán'),
        Municipio('Olanchito'),
        Municipio('Santa Rita'),
        Municipio('Sulaco'),
        Municipio('Victoria'),
        Municipio('Yorito'),
      ],
    ),
  ];

  static List<String> get nombresDepartamentos =>
      lista.map((d) => d.nombre).toList();

  static List<Municipio> municipiosDe(String? departamento) {
    if (departamento == null) return const [];
    final match = lista.where((d) => d.nombre == departamento);
    return match.isEmpty ? const [] : match.first.municipios;
  }
}
